### PR TITLE
 Add redux to the project (v1.1)

### PR DESCRIPTION
**Pull request by mrjuda**
Re-factor bookstore (react) with redux functionalities.

- Add React Redux
- Structure the application files using a "feature folder" approach
- Use the "ducks" pattern
- Write the book's actions and reducer using the "ducks" pattern
- Write the categories' actions and reducer using the "ducks" pattern
- Configure the Redux Store

### CODE REVIEW

**Comment by omar-labana** [comment]
# **Invalid Code Review Request ⚠️❌**

Hi @ ,

While you made great effort in this project, unfortunately🚩, I cannot proceed to review your code😓.

Linters are not passing, kindly fix them.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by omar-labana — CHANGES_REQUESTED** [review]
Hi @mrjuda, 

Excellent work so far! 👌
You have implemented almost all the required features without any bugs or errors. ✔️ 
There are some cases that you need to adjust but you are almost done! 😀

## Required Changes ♻️
- [ ] Kindly move reducers and actions logic to a `redux` directory inside the `src` directory, the structure should look something like this:
```markdown
    ```
        ...
        /src
            |---/components
            |---/redux
                |--- /books
                        | books.js
                |--- /categories
                        | categories.js
                | cofigureStore.js
            | index.js
    ```
```

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by mrjuda** [comment]
> Hi @mrjuda,
> 
> Excellent work so far! ok_hand You have implemented almost all the required features without any bugs or errors. heavy_check_mark There are some cases that you need to adjust but you are almost done! grinning
> ## Required Changes recycle
> 
>     * [x]  Kindly move reducers and actions logic to a `redux` directory inside the `src` directory, the structure should look something like this:
> 
> 
> ```gfm
>     ```
>         ...
>         /src
>             |---/components
>             |---/redux
>                 |--- /books
>                         | books.js
>                 |--- /categories
>                         | categories.js
>                 | cofigureStore.js
>             | index.js
>     ```
> ```
> 
> ## Optional suggestions
> 
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
> Cheers and Happy coding!clapclapclap
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

Done, thank you :-)

**Comment by omar-labana** [comment]
# **Approved ✔️**

Hi @mrjuda

Congratulations on completing this project! 👏🏼 🎉

You have correctly implemented all of the requirements📃 correctly and without any errors⚠️ or bugs🪲.

Cheers and good luck in your next milestones! 🍀

Feel free to leave any questions or comments in the PR thread(don't forget to tag me 😄) if something is not 100% clear.

---
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request closed without merging**
